import type { Metadata } from "next";
import { Geist, DM_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/ThemeProvider";
import Header from "./components/Layout/Header";
import Footer from "./components/Layout/Footer";

const dmMono = DM_Mono({
  weight: ["300", "400", "500"],
  variable: "--font-dm-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`
          ${dmMono.variable} 
          antialiased 
          bg-[#e8e8e8] text-slate-900 
          dark:bg-zinc-950 dark:text-slate-50
          transition-colors duration-300
        `}
        style={{ backgroundImage: "url('/images/background.png')", backgroundSize: "cover", backgroundPosition: "center" }}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange={false}>
          <Header />
          {children}
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
